### ISSUE TITLE
SQSCANGHA-25 Just broke our Maven builds

### ISSUE THREAD

**Issue by rickjennings** [SonarSource/sonarqube-scan-action#112]
This can be redacted/ deleted. We've rolled back from using master branch to a pinned version instead for the time-being.

**Comment by macherius-dlh** [comment]
Same for the Gradle build, same workaround applied. This works for me.
```
        uses: sonarsource/sonarqube-scan-action@6abcb2537c297b61a7310bada652d7ef3f71fc08
#        uses: sonarsource/sonarqube-scan-action@master
```
From what I see the change must be in the base image's shell processor `bash`.

https://github.com/SonarSource/sonarqube-scan-action/blob/be64f357263a9a69c6488e9bdc6f666f9783049b/entrypoint.sh#L28C10-L28C50
always had a spurious `%` sign in the variable name. This probably had disabled the condition, so the `exit 1` due to detected `build.gradle` never happened. 
The latest `main`build now correctly triggers at that if, and bails out with the expected message
```
Gradle project detected. You should use the SonarQube plugin for Gradle during build rather than using this GitHub Action.
```

My request would be to restore the old behaviour by simply deleting the check. Using the action and properties worked for 2 years in my projects, I don't understand why forcing the Gradle plugin is an improvement.

**Comment by macherius** [comment]
https://github.com/SonarSource/sonarqube-scan-action/blob/41cbf9162a34e090ab37486af98549ac8510f444/entrypoint.sh#L28
is the breaking change

**Comment by tobiwein** [comment]
Alternatives for Java, .NET, and C/C++ projects
https://github.com/SonarSource/sonarqube-scan-action?tab=readme-ov-file#alternatives-for-java-net-and-cc-projects

**Comment by bhag005** [comment]
changing from @master to v2.0.2 works.

**Comment by marcin-sowa** [comment]
In one of my client this change affected around 1000 repositories.
They are paying for Ent version, this needs to be reverted ASAP.

**Comment by marcin-sowa** [comment]
U can't scan java 11 using maven/gradle when using latest Sonar as it's require 17 runtime for scanner.
This action was only simple solution to scan legacy SDKs on latest Sonar version.

**Comment by andrewpolemeni** [comment]
We are having the same issue in Gradle builds as well with the same error.

**Comment by nachtgold** [comment]
As it is written in https://github.com/SonarSource/sonarqube-scan-action/blob/master/Dockerfile#L8 - with one scan run, scan several ecosystems. Especially with Sonar [<10.4 (plugin loader fix)](https://www.sonarsource.com/products/sonarqube/whats-new/sonarqube-10-4/#faster-scan-times), this is absolutely necessary in order to be ready at some point.

Therefore, in my opinion, both checks in https://github.com/SonarSource/sonarqube-scan-action/blob/master/entrypoint.sh#L23-L31 should be removed or converted into a warning.

**Comment by henryju** [comment]
Sorry for the noise, we are about to [change](https://github.com/SonarSource/sonarqube-scan-action/pull/117) the behavior to not fail the build, but simply log a message.

We will also update our documentation to not recommend using the master of the action.
